PORT = 5005
HOST = "127.0.0.1"

MODELS_DIR = "models"

GAMMA = 0.99
LEARNING_RATE = 3e-4
FORCE_X_CLIP = 1.0
NORMALIZE_RETURNS = False
SAVE_EVERY_EPISODES = 5
MULTI_AGENT_AVG_TRAJECTORIES = True

DIAG_LOG_EVERY_N_STEPS = 60

ENTROPY_COEF_START = 0.03
ENTROPY_COEF_END = 0.003
ENTROPY_DECAY_STEPS = 8000

ELITE_WEIGHT = 2.5

GAP_SHAPING_ENABLED = True
GAP_SHAPING_W_X = 0.06
GAP_SHAPING_W_Z = 0.0
